import { Template } from '../types';

// Production-ready website templates for hosting
export const hostingTemplates: Template[] = [
    {
        id: 'tmpl_portfolio',
        name: 'Portfolio Website',
        framework: 'HTML/CSS/JS',
        description: 'Stunning portfolio to showcase your creative work. Perfect for designers, photographers, and artists.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=html,css,js&theme=dark',
        previewUrl: 'https://opendev-labs.github.io/templates/portfolio',
        features: ['Responsive gallery', 'Contact form', 'About section', 'Project showcase'],
        category: 'Creative',
    },
    {
        id: 'tmpl_ecommerce',
        name: 'E-Commerce Store',
        framework: 'Next.js',
        description: 'Complete online store with product listings, cart, and checkout. Start selling in minutes.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=nextjs,tailwind&theme=dark',
        previewUrl: 'https://opendev-labs.github.io/templates/ecommerce',
        features: ['Product catalog', 'Shopping cart', 'Checkout flow', 'Admin dashboard'],
        category: 'Business',
    },
    {
        id: 'tmpl_saas_landing',
        name: 'SaaS Landing Page',
        framework: 'React',
        description: 'High-converting landing page for your software product. Built for maximum conversions.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=react,vite&theme=dark',
        previewUrl: 'https://opendev-labs.github.io/templates/saas',
        features: ['Hero section', 'Pricing table', 'Features showcase', 'CTA buttons'],
        category: 'Marketing',
    },
    {
        id: 'tmpl_agency',
        name: 'Agency Website',
        framework: 'Astro',
        description: 'Professional website for digital agencies and creative studios. Showcase your services and portfolio.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=astro,tailwind&theme=dark',
        features: ['Services page', 'Team profiles', 'Case studies', 'Client testimonials'],
        category: 'Business',
    },
    {
        id: 'tmpl_restaurant',
        name: 'Restaurant/Cafe',
        framework: 'HTML/CSS/JS',
        description: 'Appetizing website for restaurants and cafes. Menu display, reservations, and location.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=html,css&theme=dark',
        features: ['Digital menu', 'Reservation system', 'Gallery', 'Contact & hours'],
        category: 'Local Business',
    },
    {
        id: 'tmpl_realestate',
        name: 'Real Estate',
        framework: 'Next.js',
        description: 'Property listing website. Showcase homes, condos, and commercial properties with style.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=nextjs,postgres&theme=dark',
        features: ['Property listings', 'Search & filter', 'Agent profiles', 'Virtual tours'],
        category: 'Business',
    },
    {
        id: 'tmpl_blog',
        name: 'Blog/Magazine',
        framework: 'Astro',
        description: 'Content publishing platform. Perfect for bloggers, journalists, and content creators.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=astro,md&theme=dark',
        features: ['Article management', 'Categories & tags', 'Author pages', 'RSS feed'],
        category: 'Publishing',
    },
    {
        id: 'tmpl_startup',
        name: 'Startup Landing',
        framework: 'React',
        description: 'Launch your startup MVP. Clean, modern design optimized for early-stage companies.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=react,tailwind&theme=dark',
        features: ['Product demo', 'Waitlist signup', 'Feature highlights', 'Investor deck'],
        category: 'Startup',
    },
    {
        id: 'tmpl_personal_brand',
        name: 'Personal Brand',
        framework: 'HTML/CSS/JS',
        description: 'Build your personal brand. Perfect for creators, influencers, and thought leaders.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=html,js&theme=dark',
        features: ['Bio & story', 'Social links', 'Content hub', 'Newsletter signup'],
        category: 'Personal',
    },
    {
        id: 'tmpl_custom',
        name: 'Custom Blank',
        framework: 'Custom',
        description: 'Start from scratch. Build exactly what you need with a clean, minimal foundation.',
        author: 'opendev-labs',
        imageUrl: 'https://skillicons.dev/icons?i=html,css,js&theme=dark',
        features: ['Blank canvas', 'Basic structure', 'Modern tooling', 'Full flexibility'],
        category: 'Custom',
    },
];
