export const REAL_TEMPLATES: Record<string, Record<string, string>> = {
    'landing-page': {
        'src/App.tsx': 'export default function App() { return <div className="min-h-screen bg-black text-white flex items-center justify-center font-sans tracking-tighter"><div className="text-center"><h1 className="text-8xl font-black mb-4">OPNDV.</h1><p className="text-zinc-500 font-medium uppercase tracking-[0.3em] text-sm">Neural Landing Fabric</p></div></div>; }',
        'src/index.css': '@tailwind base; @tailwind components; @tailwind utilities; body { margin: 0; background: black; color: white; transition: all 0.5s ease; }',
        'package.json': '{"name": "opendev-landing-page", "version": "1.1.0", "dependencies": {"react": "^18.2.0", "react-dom": "^18.2.0", "framer-motion": "^10.12.16", "lucide-react": "^0.244.0"}}',
        'public/index.html': '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Genesis Node | opendev-labs</title></head><body class="bg-black"> <div id="root"></div> </body></html>'
    },
    'nextjs-starter': {
        'app/page.tsx': 'import React from "react";\n\nexport default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-center bg-black text-white p-24 font-sans">\n      <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[\'\'] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-zinc-200 after:via-zinc-200 after:blur-2xl after:content-[\'\'] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-zinc-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]">\n        <h1 className="text-7xl font-bold tracking-tighter italic">NEXUS.NODE</h1>\n      </div>\n      <div className="mt-12 grid text-center lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-4 lg:text-left">\n        <p className="m-0 max-w-[30ch] text-sm opacity-50 text-zinc-400 font-mono tracking-widest uppercase">Initializing core protocols...</p>\n      </div>\n    </main>\n  );\n}\n',
        'app/layout.tsx': 'import "./globals.css";\nimport { Inter } from "next/font/google";\n\nconst inter = Inter({ subsets: ["latin"] });\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body className={inter.className}>{children}</body>\n    </html>\n  );\n}\n',
        'app/globals.css': '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --foreground-rgb: 255, 255, 255;\n  --background-start-rgb: 0, 0, 0;\n  --background-end-rgb: 0, 0, 0;\n}\n\nbody {\n  color: rgb(var(--foreground-rgb));\n  background: linear-gradient(to bottom, transparent, rgb(var(--background-end-rgb))) rgb(var(--background-start-rgb));\n}\n',
        'package.json': '{"name": "opendev-nexus-node", "version": "0.1.0", "private": true, "scripts": {"dev": "next dev", "build": "next build", "start": "next start", "lint": "next lint"}, "dependencies": {"next": "14.0.0", "react": "^18", "react-dom": "^18", "lucide-react": "^0.284.0"}, "devDependencies": {"typescript": "^5", "@types/node": "^20", "@types/react": "^18", "@types/react-dom": "^18", "autoprefixer": "^10.0.1", "postcss": "^8", "tailwindcss": "^3.3.0", "eslint": "^8", "eslint-config-next": "14.0.0"}}'
    },
    'vite-react': {
        'src/App.tsx': 'import React from "react";\n\nfunction App() {\n  return (\n    <div className="min-h-screen bg-[#050505] text-white flex flex-col items-center justify-center p-8 font-sans">\n      <div className="max-w-2xl w-full border border-zinc-900 p-12 bg-zinc-950/50 backdrop-blur-3xl relative overflow-hidden group">\n        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-orange-500 to-transparent opacity-50" />\n        <h1 className="text-5xl font-black tracking-tighter mb-6 group-hover:text-orange-500 transition-colors">ELITE.NODE</h1>\n        <p className="text-zinc-500 text-lg font-medium leading-relaxed mb-8">Synchronizing high-fidelity React interface with local mesh cluster.</p>\n        <div className="flex gap-4">\n          <div className="px-4 py-2 border border-zinc-800 text-[10px] font-bold tracking-widest uppercase text-zinc-400">Status: Operational</div>\n          <div className="px-4 py-2 border border-zinc-800 text-[10px] font-bold tracking-widest uppercase text-zinc-400">Node: Localhost</div>\n        </div>\n      </div>\n    </div>\n  );\n}\n\nexport default App;\n',
        'src/index.css': '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  margin: 0;\n  background: #050505;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n',
        'package.json': '{"name": "opendev-elite-react", "private": true, "version": "0.0.0", "type": "module", "scripts": {"dev": "vite", "build": "tsc && vite build", "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0", "preview": "vite preview"}, "dependencies": {"react": "^18.2.0", "react-dom": "^18.2.0", "framer-motion": "^10.12.16"}, "devDependencies": {"@types/react": "^18.2.14", "@types/react-dom": "^18.2.6", "@typescript-eslint/eslint-plugin": "^5.61.0", "@typescript-eslint/parser": "^5.61.0", "@vitejs/plugin-react": "^4.0.1", "autoprefixer": "^10.4.14", "eslint": "^8.44.0", "eslint-plugin-react-hooks": "^4.6.0", "eslint-plugin-react-refresh": "^0.4.1", "postcss": "^8.4.24", "tailwindcss": "^3.3.2", "typescript": "^5.0.2", "vite": "^4.4.0"}}'
    },
    'default': {
        'src/App.tsx': 'export default function App() { return <div className="min-h-screen bg-black text-white flex items-center justify-center font-sans"><div><h1 className="text-4xl font-black tracking-tighter">GENESIS.NODE</h1><p className="text-zinc-500 mt-2 uppercase tracking-widest text-xs">Ready for initialization</p></div></div>; }',
        'package.json': '{"name": "opendev-alpha-node", "version": "1.0.0", "dependencies": {"react": "latest", "react-dom": "latest"}}'
    }
};
